server:
  port: 9080
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:h2:./.local-db/data
  h2:
    console:
      enabled: true
      path: /h2-console # http://localhost:9080/h2-console (leave username and password empty)
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
springdoc:
  paths-to-match: /api/v1/**,/actuator/**
  show-actuator: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
        #health,info,beans,metrics,startup
  endpoint:
    health:
      show-details: always
      show-components: always

